# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 321596eec16428568f9ed758a6ef1855fb825dccd24de16da0baa13a145712ab79d5bd696206e9b0b8239db9866b908f7057df376e903f5c88a7bf5703476cd4

test:
  secret_key_base: 74fe1bf96785a3837e45bd40317e935af3608bf3da7968e093c4dd112e26eca257c3d0e401344e89c5b6adef3b222ae0e393c6dcf4df6ee103d0fb61e0bc49a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
